sylius_admin:
    resource: "@SyliusAdminBundle/Resources/config/routing.yml"
    prefix: '/%sylius_admin.path_name%'

sylius_paypal_admin:
    resource: "@SyliusPayPalPlugin/Resources/config/admin_routing.yml"
    prefix: '/%sylius_admin.path_name%'
    
app_admin_book:
    resource: |
        alias: app.book
        except: ['show']
        section: admin
        templates: "@SyliusAdmin\\Crud"
        redirect: update
    type: sylius.resource
    prefix: /admin
